[package]
name = "diameter"
version = "0.1.0"
edition = "2024"

[features]
default = ["print"]
print = []

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
nom = "8.0.0"
nom_locate = "5.0.0"
